export type CatalogSource = {
  name: string;
  homepageUrl: string;
  country: "US";
  language: "en";
  spectrum: "left" | "lean_left" | "center" | "lean_right" | "right";
  sourceType: "wire" | "mainstream" | "partisan" | "local" | "opinion_heavy" | "policy";
  ratingSource: string;
  ratingUrl?: string;
  gdeltDomain: string;
  enabled: boolean;
};

export const sourceCatalog: CatalogSource[] = [
  {
    name: "Associated Press",
    homepageUrl: "https://apnews.com",
    country: "US",
    language: "en",
    spectrum: "center",
    sourceType: "wire",
    ratingSource: "starter-catalog",
    gdeltDomain: "apnews.com",
    enabled: true,
  },
  {
    name: "Reuters",
    homepageUrl: "https://www.reuters.com",
    country: "US",
    language: "en",
    spectrum: "center",
    sourceType: "wire",
    ratingSource: "starter-catalog",
    gdeltDomain: "reuters.com",
    enabled: true,
  },
  {
    name: "NPR",
    homepageUrl: "https://www.npr.org",
    country: "US",
    language: "en",
    spectrum: "lean_left",
    sourceType: "mainstream",
    ratingSource: "starter-catalog",
    gdeltDomain: "npr.org",
    enabled: true,
  },
  {
    name: "PBS NewsHour",
    homepageUrl: "https://www.pbs.org/newshour",
    country: "US",
    language: "en",
    spectrum: "center",
    sourceType: "mainstream",
    ratingSource: "starter-catalog",
    gdeltDomain: "pbs.org",
    enabled: true,
  },
  {
    name: "CNN",
    homepageUrl: "https://www.cnn.com",
    country: "US",
    language: "en",
    spectrum: "left",
    sourceType: "mainstream",
    ratingSource: "starter-catalog",
    gdeltDomain: "cnn.com",
    enabled: true,
  },
  {
    name: "MSNBC",
    homepageUrl: "https://www.msnbc.com",
    country: "US",
    language: "en",
    spectrum: "left",
    sourceType: "opinion_heavy",
    ratingSource: "starter-catalog",
    gdeltDomain: "msnbc.com",
    enabled: true,
  },
  {
    name: "The Atlantic",
    homepageUrl: "https://www.theatlantic.com",
    country: "US",
    language: "en",
    spectrum: "lean_left",
    sourceType: "mainstream",
    ratingSource: "starter-catalog",
    gdeltDomain: "theatlantic.com",
    enabled: true,
  },
  {
    name: "Vox",
    homepageUrl: "https://www.vox.com",
    country: "US",
    language: "en",
    spectrum: "left",
    sourceType: "mainstream",
    ratingSource: "starter-catalog",
    gdeltDomain: "vox.com",
    enabled: true,
  },
  {
    name: "The Hill",
    homepageUrl: "https://thehill.com",
    country: "US",
    language: "en",
    spectrum: "center",
    sourceType: "mainstream",
    ratingSource: "starter-catalog",
    gdeltDomain: "thehill.com",
    enabled: true,
  },
  {
    name: "Politico",
    homepageUrl: "https://www.politico.com",
    country: "US",
    language: "en",
    spectrum: "center",
    sourceType: "mainstream",
    ratingSource: "starter-catalog",
    gdeltDomain: "politico.com",
    enabled: true,
  },
  {
    name: "Wall Street Journal",
    homepageUrl: "https://www.wsj.com",
    country: "US",
    language: "en",
    spectrum: "lean_right",
    sourceType: "mainstream",
    ratingSource: "starter-catalog",
    gdeltDomain: "wsj.com",
    enabled: true,
  },
  {
    name: "Fox News",
    homepageUrl: "https://www.foxnews.com",
    country: "US",
    language: "en",
    spectrum: "right",
    sourceType: "mainstream",
    ratingSource: "starter-catalog",
    gdeltDomain: "foxnews.com",
    enabled: true,
  },
  {
    name: "National Review",
    homepageUrl: "https://www.nationalreview.com",
    country: "US",
    language: "en",
    spectrum: "right",
    sourceType: "opinion_heavy",
    ratingSource: "starter-catalog",
    gdeltDomain: "nationalreview.com",
    enabled: true,
  },
  {
    name: "Washington Examiner",
    homepageUrl: "https://www.washingtonexaminer.com",
    country: "US",
    language: "en",
    spectrum: "right",
    sourceType: "partisan",
    ratingSource: "starter-catalog",
    gdeltDomain: "washingtonexaminer.com",
    enabled: true,
  },
  {
    name: "The Dispatch",
    homepageUrl: "https://thedispatch.com",
    country: "US",
    language: "en",
    spectrum: "lean_right",
    sourceType: "opinion_heavy",
    ratingSource: "starter-catalog",
    gdeltDomain: "thedispatch.com",
    enabled: true,
  },
  {
    name: "Los Angeles Times",
    homepageUrl: "https://www.latimes.com",
    country: "US",
    language: "en",
    spectrum: "lean_left",
    sourceType: "mainstream",
    ratingSource: "starter-catalog",
    gdeltDomain: "latimes.com",
    enabled: true,
  },
  {
    name: "Chicago Tribune",
    homepageUrl: "https://www.chicagotribune.com",
    country: "US",
    language: "en",
    spectrum: "center",
    sourceType: "local",
    ratingSource: "starter-catalog",
    gdeltDomain: "chicagotribune.com",
    enabled: true,
  },
  {
    name: "Texas Tribune",
    homepageUrl: "https://www.texastribune.org",
    country: "US",
    language: "en",
    spectrum: "center",
    sourceType: "local",
    ratingSource: "starter-catalog",
    gdeltDomain: "texastribune.org",
    enabled: true,
  },
  {
    name: "Arizona Republic",
    homepageUrl: "https://www.azcentral.com",
    country: "US",
    language: "en",
    spectrum: "center",
    sourceType: "local",
    ratingSource: "starter-catalog",
    gdeltDomain: "azcentral.com",
    enabled: true,
  },
  {
    name: "Miami Herald",
    homepageUrl: "https://www.miamiherald.com",
    country: "US",
    language: "en",
    spectrum: "center",
    sourceType: "local",
    ratingSource: "starter-catalog",
    gdeltDomain: "miamiherald.com",
    enabled: true,
  },
  {
    name: "ProPublica",
    homepageUrl: "https://www.propublica.org",
    country: "US",
    language: "en",
    spectrum: "lean_left",
    sourceType: "policy",
    ratingSource: "AllSides",
    ratingUrl: "https://www.allsides.com/news-source/propublica-media-bias",
    gdeltDomain: "propublica.org",
    enabled: true,
  },
  {
    name: "SCOTUSblog",
    homepageUrl: "https://www.scotusblog.com",
    country: "US",
    language: "en",
    spectrum: "center",
    sourceType: "policy",
    ratingSource: "starter-catalog",
    gdeltDomain: "scotusblog.com",
    enabled: true,
  },
  {
    name: "Reason",
    homepageUrl: "https://reason.com",
    country: "US",
    language: "en",
    spectrum: "lean_right",
    sourceType: "opinion_heavy",
    ratingSource: "starter-catalog",
    gdeltDomain: "reason.com",
    enabled: true,
  },
  {
    name: "Brookings Institution",
    homepageUrl: "https://www.brookings.edu",
    country: "US",
    language: "en",
    spectrum: "center",
    sourceType: "policy",
    ratingSource: "AllSides",
    ratingUrl: "https://www.allsides.com/news-source/brookings-institution-media-bias",
    gdeltDomain: "brookings.edu",
    enabled: true,
  },
  {
    name: "Heritage Foundation",
    homepageUrl: "https://www.heritage.org",
    country: "US",
    language: "en",
    spectrum: "right",
    sourceType: "policy",
    ratingSource: "AllSides",
    ratingUrl: "https://www.allsides.com/news-source/heritage-foundation-media-bias",
    gdeltDomain: "heritage.org",
    enabled: true,
  },
  {
    name: "Cato Institute",
    homepageUrl: "https://www.cato.org",
    country: "US",
    language: "en",
    spectrum: "lean_right",
    sourceType: "policy",
    ratingSource: "AllSides",
    ratingUrl: "https://www.allsides.com/news-source/cato-institute-media-bias",
    gdeltDomain: "cato.org",
    enabled: true,
  },
  {
    name: "American Enterprise Institute",
    homepageUrl: "https://www.aei.org",
    country: "US",
    language: "en",
    spectrum: "lean_right",
    sourceType: "policy",
    ratingSource: "AllSides",
    ratingUrl: "https://www.allsides.com/news-source/american-enterprise-institute-media-bias",
    gdeltDomain: "aei.org",
    enabled: true,
  },
  {
    name: "Economic Policy Institute",
    homepageUrl: "https://www.epi.org",
    country: "US",
    language: "en",
    spectrum: "left",
    sourceType: "policy",
    ratingSource: "AllSides",
    ratingUrl: "https://www.allsides.com/news-source/economic-policy-institute",
    gdeltDomain: "epi.org",
    enabled: true,
  },
  {
    name: "Brennan Center for Justice",
    homepageUrl: "https://www.brennancenter.org",
    country: "US",
    language: "en",
    spectrum: "lean_left",
    sourceType: "policy",
    ratingSource: "AllSides",
    ratingUrl: "https://www.allsides.com/news-source/brennan-center-justice-media-bias",
    gdeltDomain: "brennancenter.org",
    enabled: true,
  },
  {
    name: "Bipartisan Policy Center",
    homepageUrl: "https://bipartisanpolicy.org",
    country: "US",
    language: "en",
    spectrum: "center",
    sourceType: "policy",
    ratingSource: "AllSides",
    ratingUrl: "https://www.allsides.com/news-source/bipartisan-policy-center-media-bias-0",
    gdeltDomain: "bipartisanpolicy.org",
    enabled: true,
  },
  {
    name: "KFF",
    homepageUrl: "https://www.kff.org",
    country: "US",
    language: "en",
    spectrum: "center",
    sourceType: "policy",
    ratingSource: "AllSides",
    ratingUrl: "https://www.allsides.com/news-source/kaiser-family-foundation-media-bias",
    gdeltDomain: "kff.org",
    enabled: true,
  },
  {
    name: "Center on Budget and Policy Priorities",
    homepageUrl: "https://www.cbpp.org",
    country: "US",
    language: "en",
    spectrum: "left",
    sourceType: "policy",
    ratingSource: "AllSides",
    ratingUrl: "https://www.allsides.com/news-source/center-budget-and-policy-priorities-0",
    gdeltDomain: "cbpp.org",
    enabled: true,
  },
  {
    name: "Council on Foreign Relations",
    homepageUrl: "https://www.cfr.org",
    country: "US",
    language: "en",
    spectrum: "left",
    sourceType: "policy",
    ratingSource: "AllSides",
    ratingUrl: "https://www.allsides.com/news-source/council-foreign-relations-media-bias",
    gdeltDomain: "cfr.org",
    enabled: true,
  },
  {
    name: "Foreign Affairs",
    homepageUrl: "https://www.foreignaffairs.com",
    country: "US",
    language: "en",
    spectrum: "center",
    sourceType: "policy",
    ratingSource: "AllSides",
    ratingUrl: "https://www.allsides.com/news-source/foreign-affairs-media-bias",
    gdeltDomain: "foreignaffairs.com",
    enabled: true,
  },
  {
    name: "Foundation for Individual Rights and Expression",
    homepageUrl: "https://www.thefire.org",
    country: "US",
    language: "en",
    spectrum: "center",
    sourceType: "policy",
    ratingSource: "AllSides",
    ratingUrl:
      "https://www.allsides.com/news-source/foundation-individual-rights-and-expression-media-bias",
    gdeltDomain: "thefire.org",
    enabled: true,
  },
  {
    name: "Tax Foundation",
    homepageUrl: "https://taxfoundation.org",
    country: "US",
    language: "en",
    spectrum: "lean_right",
    sourceType: "policy",
    ratingSource: "starter-catalog",
    gdeltDomain: "taxfoundation.org",
    enabled: true,
  },
  {
    name: "Urban Institute",
    homepageUrl: "https://www.urban.org",
    country: "US",
    language: "en",
    spectrum: "center",
    sourceType: "policy",
    ratingSource: "starter-catalog",
    gdeltDomain: "urban.org",
    enabled: true,
  },
  {
    name: "Migration Policy Institute",
    homepageUrl: "https://www.migrationpolicy.org",
    country: "US",
    language: "en",
    spectrum: "center",
    sourceType: "policy",
    ratingSource: "starter-catalog",
    gdeltDomain: "migrationpolicy.org",
    enabled: true,
  },
];
