export type CatalogSource = {
  name: string;
  homepageUrl: string;
  country: "US";
  language: "en";
  spectrum: "left" | "lean_left" | "center" | "lean_right" | "right";
  sourceType: "wire" | "mainstream" | "partisan" | "local" | "opinion_heavy" | "policy";
  ratingSource: string;
  ratingUrl?: string;
  accessProfile: "open" | "metered" | "hard_paywall" | "unknown";
  gdeltDomain: string;
  rssFeedUrls?: string[];
  enabled: boolean;
};

export const sourceCatalog: CatalogSource[] = [
  {
    name: "Associated Press",
    homepageUrl: "https://apnews.com",
    country: "US",
    language: "en",
    spectrum: "center",
    sourceType: "wire",
    ratingSource: "starter-catalog",
    accessProfile: "open",
    gdeltDomain: "apnews.com",
    enabled: true,
  },
  {
    name: "Reuters",
    homepageUrl: "https://www.reuters.com",
    country: "US",
    language: "en",
    spectrum: "center",
    sourceType: "wire",
    ratingSource: "starter-catalog",
    accessProfile: "open",
    gdeltDomain: "reuters.com",
    enabled: true,
  },
  {
    name: "NPR",
    homepageUrl: "https://www.npr.org",
    country: "US",
    language: "en",
    spectrum: "lean_left",
    sourceType: "mainstream",
    ratingSource: "starter-catalog",
    accessProfile: "open",
    gdeltDomain: "npr.org",
    rssFeedUrls: ["https://feeds.npr.org/1014/rss.xml"],
    enabled: true,
  },
  {
    name: "PBS NewsHour",
    homepageUrl: "https://www.pbs.org/newshour",
    country: "US",
    language: "en",
    spectrum: "center",
    sourceType: "mainstream",
    ratingSource: "starter-catalog",
    accessProfile: "open",
    gdeltDomain: "pbs.org",
    enabled: true,
  },
  {
    name: "CNN",
    homepageUrl: "https://www.cnn.com",
    country: "US",
    language: "en",
    spectrum: "left",
    sourceType: "mainstream",
    ratingSource: "starter-catalog",
    accessProfile: "open",
    gdeltDomain: "cnn.com",
    enabled: true,
  },
  {
    name: "MSNBC",
    homepageUrl: "https://www.msnbc.com",
    country: "US",
    language: "en",
    spectrum: "left",
    sourceType: "opinion_heavy",
    ratingSource: "starter-catalog",
    accessProfile: "open",
    gdeltDomain: "msnbc.com",
    enabled: true,
  },
  {
    name: "The Atlantic",
    homepageUrl: "https://www.theatlantic.com",
    country: "US",
    language: "en",
    spectrum: "lean_left",
    sourceType: "mainstream",
    ratingSource: "starter-catalog",
    accessProfile: "metered",
    gdeltDomain: "theatlantic.com",
    enabled: true,
  },
  {
    name: "Vox",
    homepageUrl: "https://www.vox.com",
    country: "US",
    language: "en",
    spectrum: "left",
    sourceType: "mainstream",
    ratingSource: "starter-catalog",
    accessProfile: "open",
    gdeltDomain: "vox.com",
    enabled: true,
  },
  {
    name: "The Hill",
    homepageUrl: "https://thehill.com",
    country: "US",
    language: "en",
    spectrum: "center",
    sourceType: "mainstream",
    ratingSource: "starter-catalog",
    accessProfile: "open",
    gdeltDomain: "thehill.com",
    rssFeedUrls: ["https://thehill.com/feed/"],
    enabled: true,
  },
  {
    name: "Politico",
    homepageUrl: "https://www.politico.com",
    country: "US",
    language: "en",
    spectrum: "center",
    sourceType: "mainstream",
    ratingSource: "starter-catalog",
    accessProfile: "metered",
    gdeltDomain: "politico.com",
    enabled: true,
  },
  {
    name: "Wall Street Journal",
    homepageUrl: "https://www.wsj.com",
    country: "US",
    language: "en",
    spectrum: "lean_right",
    sourceType: "mainstream",
    ratingSource: "starter-catalog",
    accessProfile: "metered",
    gdeltDomain: "wsj.com",
    enabled: true,
  },
  {
    name: "Fox News",
    homepageUrl: "https://www.foxnews.com",
    country: "US",
    language: "en",
    spectrum: "right",
    sourceType: "mainstream",
    ratingSource: "starter-catalog",
    accessProfile: "open",
    gdeltDomain: "foxnews.com",
    enabled: true,
  },
  {
    name: "National Review",
    homepageUrl: "https://www.nationalreview.com",
    country: "US",
    language: "en",
    spectrum: "right",
    sourceType: "opinion_heavy",
    ratingSource: "starter-catalog",
    accessProfile: "unknown",
    gdeltDomain: "nationalreview.com",
    enabled: true,
  },
  {
    name: "Washington Examiner",
    homepageUrl: "https://www.washingtonexaminer.com",
    country: "US",
    language: "en",
    spectrum: "right",
    sourceType: "partisan",
    ratingSource: "starter-catalog",
    accessProfile: "open",
    gdeltDomain: "washingtonexaminer.com",
    enabled: true,
  },
  {
    name: "The Dispatch",
    homepageUrl: "https://thedispatch.com",
    country: "US",
    language: "en",
    spectrum: "lean_right",
    sourceType: "opinion_heavy",
    ratingSource: "starter-catalog",
    accessProfile: "unknown",
    gdeltDomain: "thedispatch.com",
    enabled: true,
  },
  {
    name: "Los Angeles Times",
    homepageUrl: "https://www.latimes.com",
    country: "US",
    language: "en",
    spectrum: "lean_left",
    sourceType: "mainstream",
    ratingSource: "starter-catalog",
    accessProfile: "metered",
    gdeltDomain: "latimes.com",
    enabled: true,
  },
  {
    name: "Chicago Tribune",
    homepageUrl: "https://www.chicagotribune.com",
    country: "US",
    language: "en",
    spectrum: "center",
    sourceType: "local",
    ratingSource: "starter-catalog",
    accessProfile: "metered",
    gdeltDomain: "chicagotribune.com",
    enabled: true,
  },
  {
    name: "Texas Tribune",
    homepageUrl: "https://www.texastribune.org",
    country: "US",
    language: "en",
    spectrum: "center",
    sourceType: "local",
    ratingSource: "starter-catalog",
    accessProfile: "open",
    gdeltDomain: "texastribune.org",
    rssFeedUrls: ["https://www.texastribune.org/feeds/main/"],
    enabled: true,
  },
  {
    name: "Arizona Republic",
    homepageUrl: "https://www.azcentral.com",
    country: "US",
    language: "en",
    spectrum: "center",
    sourceType: "local",
    ratingSource: "starter-catalog",
    accessProfile: "metered",
    gdeltDomain: "azcentral.com",
    enabled: true,
  },
  {
    name: "Miami Herald",
    homepageUrl: "https://www.miamiherald.com",
    country: "US",
    language: "en",
    spectrum: "center",
    sourceType: "local",
    ratingSource: "starter-catalog",
    accessProfile: "metered",
    gdeltDomain: "miamiherald.com",
    enabled: true,
  },
  {
    name: "ProPublica",
    homepageUrl: "https://www.propublica.org",
    country: "US",
    language: "en",
    spectrum: "lean_left",
    sourceType: "policy",
    ratingSource: "AllSides",
    ratingUrl: "https://www.allsides.com/news-source/propublica-media-bias",
    accessProfile: "open",
    gdeltDomain: "propublica.org",
    rssFeedUrls: ["https://www.propublica.org/feeds/propublica/main"],
    enabled: true,
  },
  {
    name: "SCOTUSblog",
    homepageUrl: "https://www.scotusblog.com",
    country: "US",
    language: "en",
    spectrum: "center",
    sourceType: "policy",
    ratingSource: "starter-catalog",
    accessProfile: "open",
    gdeltDomain: "scotusblog.com",
    enabled: true,
  },
  {
    name: "Reason",
    homepageUrl: "https://reason.com",
    country: "US",
    language: "en",
    spectrum: "lean_right",
    sourceType: "opinion_heavy",
    ratingSource: "starter-catalog",
    accessProfile: "unknown",
    gdeltDomain: "reason.com",
    rssFeedUrls: ["https://reason.com/feed/"],
    enabled: true,
  },
  {
    name: "Brookings Institution",
    homepageUrl: "https://www.brookings.edu",
    country: "US",
    language: "en",
    spectrum: "center",
    sourceType: "policy",
    ratingSource: "AllSides",
    ratingUrl: "https://www.allsides.com/news-source/brookings-institution-media-bias",
    accessProfile: "open",
    gdeltDomain: "brookings.edu",
    enabled: true,
  },
  {
    name: "Heritage Foundation",
    homepageUrl: "https://www.heritage.org",
    country: "US",
    language: "en",
    spectrum: "right",
    sourceType: "policy",
    ratingSource: "AllSides",
    ratingUrl: "https://www.allsides.com/news-source/heritage-foundation-media-bias",
    accessProfile: "open",
    gdeltDomain: "heritage.org",
    rssFeedUrls: ["https://www.heritage.org/rss"],
    enabled: true,
  },
  {
    name: "Cato Institute",
    homepageUrl: "https://www.cato.org",
    country: "US",
    language: "en",
    spectrum: "lean_right",
    sourceType: "policy",
    ratingSource: "AllSides",
    ratingUrl: "https://www.allsides.com/news-source/cato-institute-media-bias",
    accessProfile: "open",
    gdeltDomain: "cato.org",
    enabled: true,
  },
  {
    name: "American Enterprise Institute",
    homepageUrl: "https://www.aei.org",
    country: "US",
    language: "en",
    spectrum: "lean_right",
    sourceType: "policy",
    ratingSource: "AllSides",
    ratingUrl: "https://www.allsides.com/news-source/american-enterprise-institute-media-bias",
    accessProfile: "open",
    gdeltDomain: "aei.org",
    enabled: true,
  },
  {
    name: "Economic Policy Institute",
    homepageUrl: "https://www.epi.org",
    country: "US",
    language: "en",
    spectrum: "left",
    sourceType: "policy",
    ratingSource: "AllSides",
    ratingUrl: "https://www.allsides.com/news-source/economic-policy-institute",
    accessProfile: "open",
    gdeltDomain: "epi.org",
    enabled: true,
  },
  {
    name: "Brennan Center for Justice",
    homepageUrl: "https://www.brennancenter.org",
    country: "US",
    language: "en",
    spectrum: "lean_left",
    sourceType: "policy",
    ratingSource: "AllSides",
    ratingUrl: "https://www.allsides.com/news-source/brennan-center-justice-media-bias",
    accessProfile: "open",
    gdeltDomain: "brennancenter.org",
    enabled: true,
  },
  {
    name: "Bipartisan Policy Center",
    homepageUrl: "https://bipartisanpolicy.org",
    country: "US",
    language: "en",
    spectrum: "center",
    sourceType: "policy",
    ratingSource: "AllSides",
    ratingUrl: "https://www.allsides.com/news-source/bipartisan-policy-center-media-bias-0",
    accessProfile: "open",
    gdeltDomain: "bipartisanpolicy.org",
    enabled: true,
  },
  {
    name: "KFF",
    homepageUrl: "https://www.kff.org",
    country: "US",
    language: "en",
    spectrum: "center",
    sourceType: "policy",
    ratingSource: "AllSides",
    ratingUrl: "https://www.allsides.com/news-source/kaiser-family-foundation-media-bias",
    accessProfile: "open",
    gdeltDomain: "kff.org",
    rssFeedUrls: ["https://www.kff.org/feed/"],
    enabled: true,
  },
  {
    name: "Center on Budget and Policy Priorities",
    homepageUrl: "https://www.cbpp.org",
    country: "US",
    language: "en",
    spectrum: "left",
    sourceType: "policy",
    ratingSource: "AllSides",
    ratingUrl: "https://www.allsides.com/news-source/center-budget-and-policy-priorities-0",
    accessProfile: "open",
    gdeltDomain: "cbpp.org",
    enabled: true,
  },
  {
    name: "Council on Foreign Relations",
    homepageUrl: "https://www.cfr.org",
    country: "US",
    language: "en",
    spectrum: "left",
    sourceType: "policy",
    ratingSource: "AllSides",
    ratingUrl: "https://www.allsides.com/news-source/council-foreign-relations-media-bias",
    accessProfile: "open",
    gdeltDomain: "cfr.org",
    enabled: true,
  },
  {
    name: "Foreign Affairs",
    homepageUrl: "https://www.foreignaffairs.com",
    country: "US",
    language: "en",
    spectrum: "center",
    sourceType: "policy",
    ratingSource: "AllSides",
    ratingUrl: "https://www.allsides.com/news-source/foreign-affairs-media-bias",
    accessProfile: "metered",
    gdeltDomain: "foreignaffairs.com",
    enabled: true,
  },
  {
    name: "Foundation for Individual Rights and Expression",
    homepageUrl: "https://www.thefire.org",
    country: "US",
    language: "en",
    spectrum: "center",
    sourceType: "policy",
    ratingSource: "AllSides",
    ratingUrl:
      "https://www.allsides.com/news-source/foundation-individual-rights-and-expression-media-bias",
    accessProfile: "open",
    gdeltDomain: "thefire.org",
    enabled: true,
  },
  {
    name: "Tax Foundation",
    homepageUrl: "https://taxfoundation.org",
    country: "US",
    language: "en",
    spectrum: "lean_right",
    sourceType: "policy",
    ratingSource: "starter-catalog",
    accessProfile: "open",
    gdeltDomain: "taxfoundation.org",
    enabled: true,
  },
  {
    name: "Urban Institute",
    homepageUrl: "https://www.urban.org",
    country: "US",
    language: "en",
    spectrum: "center",
    sourceType: "policy",
    ratingSource: "starter-catalog",
    accessProfile: "open",
    gdeltDomain: "urban.org",
    enabled: true,
  },
  {
    name: "Migration Policy Institute",
    homepageUrl: "https://www.migrationpolicy.org",
    country: "US",
    language: "en",
    spectrum: "center",
    sourceType: "policy",
    ratingSource: "starter-catalog",
    accessProfile: "open",
    gdeltDomain: "migrationpolicy.org",
    enabled: true,
  },
  {
    name: "Axios",
    homepageUrl: "https://www.axios.com",
    country: "US",
    language: "en",
    spectrum: "lean_left",
    sourceType: "mainstream",
    ratingSource: "AllSides",
    ratingUrl: "https://www.allsides.com/news-source/axios-media-bias",
    accessProfile: "open",
    gdeltDomain: "axios.com",
    enabled: true,
  },
  {
    name: "Semafor",
    homepageUrl: "https://www.semafor.com",
    country: "US",
    language: "en",
    spectrum: "lean_left",
    sourceType: "mainstream",
    ratingSource: "AllSides",
    ratingUrl: "https://www.allsides.com/news-source/semafor-media-bias",
    accessProfile: "open",
    gdeltDomain: "semafor.com",
    enabled: true,
  },
  {
    name: "RealClearPolitics",
    homepageUrl: "https://www.realclearpolitics.com",
    country: "US",
    language: "en",
    spectrum: "lean_right",
    sourceType: "mainstream",
    ratingSource: "AllSides",
    ratingUrl: "https://www.allsides.com/news-source/realclearpolitics-media-bias",
    accessProfile: "open",
    gdeltDomain: "realclearpolitics.com",
    enabled: true,
  },
  {
    name: "New York Post",
    homepageUrl: "https://nypost.com",
    country: "US",
    language: "en",
    spectrum: "lean_right",
    sourceType: "mainstream",
    ratingSource: "AllSides",
    ratingUrl: "https://www.allsides.com/news-source/new-york-post",
    accessProfile: "open",
    gdeltDomain: "nypost.com",
    enabled: true,
  },
  {
    name: "Daily Caller",
    homepageUrl: "https://dailycaller.com",
    country: "US",
    language: "en",
    spectrum: "right",
    sourceType: "partisan",
    ratingSource: "AllSides",
    ratingUrl: "https://www.allsides.com/news-source/daily-caller-media-bias",
    accessProfile: "open",
    gdeltDomain: "dailycaller.com",
    enabled: true,
  },
  {
    name: "Daily Wire",
    homepageUrl: "https://www.dailywire.com",
    country: "US",
    language: "en",
    spectrum: "right",
    sourceType: "opinion_heavy",
    ratingSource: "AllSides",
    ratingUrl: "https://www.allsides.com/news-source/daily-wire-media-bias",
    accessProfile: "open",
    gdeltDomain: "dailywire.com",
    enabled: true,
  },
  {
    name: "The Federalist",
    homepageUrl: "https://thefederalist.com",
    country: "US",
    language: "en",
    spectrum: "right",
    sourceType: "opinion_heavy",
    ratingSource: "AllSides",
    ratingUrl: "https://www.allsides.com/news-source/federalist-media-bias",
    accessProfile: "open",
    gdeltDomain: "thefederalist.com",
    enabled: true,
  },
  {
    name: "Pew Research Center",
    homepageUrl: "https://www.pewresearch.org",
    country: "US",
    language: "en",
    spectrum: "center",
    sourceType: "policy",
    ratingSource: "starter-catalog",
    accessProfile: "open",
    gdeltDomain: "pewresearch.org",
    enabled: true,
  },
  {
    name: "RAND Corporation",
    homepageUrl: "https://www.rand.org",
    country: "US",
    language: "en",
    spectrum: "center",
    sourceType: "policy",
    ratingSource: "starter-catalog",
    accessProfile: "open",
    gdeltDomain: "rand.org",
    enabled: true,
  },
  {
    name: "Niskanen Center",
    homepageUrl: "https://www.niskanencenter.org",
    country: "US",
    language: "en",
    spectrum: "center",
    sourceType: "policy",
    ratingSource: "starter-catalog",
    accessProfile: "open",
    gdeltDomain: "niskanencenter.org",
    enabled: true,
  },
  {
    name: "Manhattan Institute",
    homepageUrl: "https://manhattan.institute",
    country: "US",
    language: "en",
    spectrum: "lean_right",
    sourceType: "policy",
    ratingSource: "starter-catalog",
    accessProfile: "open",
    gdeltDomain: "manhattan.institute",
    enabled: true,
  },
  {
    name: "Mercatus Center",
    homepageUrl: "https://www.mercatus.org",
    country: "US",
    language: "en",
    spectrum: "lean_right",
    sourceType: "policy",
    ratingSource: "starter-catalog",
    accessProfile: "open",
    gdeltDomain: "mercatus.org",
    enabled: true,
  },
  {
    name: "Institute for Justice",
    homepageUrl: "https://ij.org",
    country: "US",
    language: "en",
    spectrum: "lean_right",
    sourceType: "policy",
    ratingSource: "starter-catalog",
    accessProfile: "open",
    gdeltDomain: "ij.org",
    enabled: true,
  },
  {
    name: "ACLU",
    homepageUrl: "https://www.aclu.org",
    country: "US",
    language: "en",
    spectrum: "left",
    sourceType: "policy",
    ratingSource: "starter-catalog",
    accessProfile: "open",
    gdeltDomain: "aclu.org",
    enabled: true,
  },
  {
    name: "Vera Institute of Justice",
    homepageUrl: "https://www.vera.org",
    country: "US",
    language: "en",
    spectrum: "left",
    sourceType: "policy",
    ratingSource: "starter-catalog",
    accessProfile: "open",
    gdeltDomain: "vera.org",
    enabled: true,
  },
  {
    name: "R Street Institute",
    homepageUrl: "https://www.rstreet.org",
    country: "US",
    language: "en",
    spectrum: "center",
    sourceType: "policy",
    ratingSource: "starter-catalog",
    accessProfile: "open",
    gdeltDomain: "rstreet.org",
    enabled: true,
  },
  {
    name: "OpenSecrets",
    homepageUrl: "https://www.opensecrets.org",
    country: "US",
    language: "en",
    spectrum: "center",
    sourceType: "policy",
    ratingSource: "starter-catalog",
    accessProfile: "open",
    gdeltDomain: "opensecrets.org",
    enabled: true,
  },
  {
    name: "Institute for Progress",
    homepageUrl: "https://ifp.org",
    country: "US",
    language: "en",
    spectrum: "center",
    sourceType: "policy",
    ratingSource: "starter-catalog",
    accessProfile: "open",
    gdeltDomain: "ifp.org",
    enabled: true,
  },
  {
    name: "Washington Times",
    homepageUrl: "https://www.washingtontimes.com",
    country: "US",
    language: "en",
    spectrum: "right",
    sourceType: "mainstream",
    ratingSource: "starter-catalog",
    accessProfile: "open",
    gdeltDomain: "washingtontimes.com",
    enabled: true,
  },
  {
    name: "Boston Globe",
    homepageUrl: "https://www.bostonglobe.com",
    country: "US",
    language: "en",
    spectrum: "lean_left",
    sourceType: "local",
    ratingSource: "starter-catalog",
    accessProfile: "metered",
    gdeltDomain: "bostonglobe.com",
    enabled: true,
  },
  {
    name: "Philadelphia Inquirer",
    homepageUrl: "https://www.inquirer.com",
    country: "US",
    language: "en",
    spectrum: "lean_left",
    sourceType: "local",
    ratingSource: "starter-catalog",
    accessProfile: "metered",
    gdeltDomain: "inquirer.com",
    enabled: true,
  },
  {
    name: "Seattle Times",
    homepageUrl: "https://www.seattletimes.com",
    country: "US",
    language: "en",
    spectrum: "center",
    sourceType: "local",
    ratingSource: "starter-catalog",
    accessProfile: "metered",
    gdeltDomain: "seattletimes.com",
    enabled: true,
  },
];
